files:
  - source: /Flow.Launcher/Languages/*.xaml
    translation: /Flow.Launcher.Translations/%two_letters_code%.xaml
  - source: /Plugins/Flow.Launcher.Plugin.BrowserBookmark/Languages/*.xaml
    translation: /Plugins/Flow.Launcher.Plugin.BrowserBookmark/Translations/%two_letters_code%.xaml
