# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'

env:
  days-before-stale: 60
  days-before-close: 7
  exempt-issue-labels: 'keep-fresh'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open ${{ env.days-before-stale }} days with no activity. Remove stale label or comment or this will be closed in ${{ env.days-before-stale }} days.\n\nAlternatively this issue can be kept open by adding one of the following labels:\n${{ env.exempt-issue-labels }}'
          days-before-stale: ${{ env.days-before-stale }}
          days-before-close: ${{ env.days-before-close }}
          days-before-pr-close: -1
          exempt-all-milestones: true
          close-issue-message: 'This issue was closed because it has been stale for 7 days with no activity. If you feel this issue still needs attention please feel free to reopen.'
          stale-pr-label: 'no-pr-activity'
          exempt-issue-labels: ${{ env.exempt-issue-labels }}
          exempt-pr-labels: 'keep-fresh,awaiting-approval,work-in-progress'
