name: Publish to Winget

# Required secrets
#
# WINGET_TOKEN:
# Token used to submit a manifest PR to microsoft/winget-pkgs
# on behalf of Flow-Launcher.Flow-Launcher.

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Flow-Launcher.Flow-Launcher
          token: ${{ secrets.WINGET_TOKEN }}
